# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/binlog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/binlog.proto',
  package='slave.binlog',
  syntax='proto2',
  serialized_pb=_b('\n\x12proto/binlog.proto\x12\x0cslave.binlog\x1a\x14gogoproto/gogo.proto\"\x8c\x01\n\x06\x43olumn\x12\x16\n\x07is_null\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x13\n\x0bint64_value\x18\x02 \x01(\x03\x12\x14\n\x0cuint64_value\x18\x03 \x01(\x04\x12\x14\n\x0c\x64ouble_value\x18\x04 \x01(\x01\x12\x13\n\x0b\x62ytes_value\x18\x05 \x01(\x0c\x12\x14\n\x0cstring_value\x18\x06 \x01(\t\"X\n\nColumnInfo\x12\x12\n\x04name\x18\x01 \x01(\tB\x04\xc8\xde\x1f\x00\x12\x18\n\nmysql_type\x18\x02 \x01(\tB\x04\xc8\xde\x1f\x00\x12\x1c\n\x0eis_primary_key\x18\x03 \x01(\x08\x42\x04\xc8\xde\x1f\x00\",\n\x03Row\x12%\n\x07\x63olumns\x18\x01 \x03(\x0b\x32\x14.slave.binlog.Column\"\x8f\x01\n\x05Table\x12\x13\n\x0bschema_name\x18\x01 \x01(\t\x12\x12\n\ntable_name\x18\x02 \x01(\t\x12-\n\x0b\x63olumn_info\x18\x03 \x03(\x0b\x32\x18.slave.binlog.ColumnInfo\x12.\n\tmutations\x18\x04 \x03(\x0b\x32\x1b.slave.binlog.TableMutation\"\x80\x01\n\rTableMutation\x12(\n\x04type\x18\x01 \x02(\x0e\x32\x1a.slave.binlog.MutationType\x12\x1e\n\x03row\x18\x02 \x02(\x0b\x32\x11.slave.binlog.Row\x12%\n\nchange_row\x18\x03 \x01(\x0b\x32\x11.slave.binlog.Row\".\n\x07\x44MLData\x12#\n\x06tables\x18\x01 \x03(\x0b\x32\x13.slave.binlog.Table\"E\n\x07\x44\x44LData\x12\x13\n\x0bschema_name\x18\x01 \x01(\t\x12\x12\n\ntable_name\x18\x02 \x01(\t\x12\x11\n\tddl_query\x18\x03 \x01(\x0c\"\xa1\x01\n\x06\x42inlog\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x18.slave.binlog.BinlogTypeB\x04\xc8\xde\x1f\x00\x12\x17\n\tcommit_ts\x18\x02 \x01(\x03\x42\x04\xc8\xde\x1f\x00\x12\'\n\x08\x64ml_data\x18\x03 \x01(\x0b\x32\x15.slave.binlog.DMLData\x12\'\n\x08\x64\x64l_data\x18\x04 \x01(\x0b\x32\x15.slave.binlog.DDLData*2\n\x0cMutationType\x12\n\n\x06Insert\x10\x00\x12\n\n\x06Update\x10\x01\x12\n\n\x06\x44\x65lete\x10\x02*\x1e\n\nBinlogType\x12\x07\n\x03\x44ML\x10\x00\x12\x07\n\x03\x44\x44L\x10\x01\x42\x0c\xc8\xe2\x1e\x01\xe0\xe2\x1e\x01\xd0\xe2\x1e\x01')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])

_MUTATIONTYPE = _descriptor.EnumDescriptor(
  name='MutationType',
  full_name='slave.binlog.MutationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Insert', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Update', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Delete', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=897,
  serialized_end=947,
)
_sym_db.RegisterEnumDescriptor(_MUTATIONTYPE)

MutationType = enum_type_wrapper.EnumTypeWrapper(_MUTATIONTYPE)
_BINLOGTYPE = _descriptor.EnumDescriptor(
  name='BinlogType',
  full_name='slave.binlog.BinlogType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DML', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DDL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=949,
  serialized_end=979,
)
_sym_db.RegisterEnumDescriptor(_BINLOGTYPE)

BinlogType = enum_type_wrapper.EnumTypeWrapper(_BINLOGTYPE)
Insert = 0
Update = 1
Delete = 2
DML = 0
DDL = 1



_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='slave.binlog.Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_null', full_name='slave.binlog.Column.is_null', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int64_value', full_name='slave.binlog.Column.int64_value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uint64_value', full_name='slave.binlog.Column.uint64_value', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='slave.binlog.Column.double_value', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_value', full_name='slave.binlog.Column.bytes_value', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='slave.binlog.Column.string_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=199,
)


_COLUMNINFO = _descriptor.Descriptor(
  name='ColumnInfo',
  full_name='slave.binlog.ColumnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='slave.binlog.ColumnInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mysql_type', full_name='slave.binlog.ColumnInfo.mysql_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_primary_key', full_name='slave.binlog.ColumnInfo.is_primary_key', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=289,
)


_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='slave.binlog.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columns', full_name='slave.binlog.Row.columns', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=335,
)


_TABLE = _descriptor.Descriptor(
  name='Table',
  full_name='slave.binlog.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema_name', full_name='slave.binlog.Table.schema_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table_name', full_name='slave.binlog.Table.table_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column_info', full_name='slave.binlog.Table.column_info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mutations', full_name='slave.binlog.Table.mutations', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=481,
)


_TABLEMUTATION = _descriptor.Descriptor(
  name='TableMutation',
  full_name='slave.binlog.TableMutation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='slave.binlog.TableMutation.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row', full_name='slave.binlog.TableMutation.row', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='change_row', full_name='slave.binlog.TableMutation.change_row', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=612,
)


_DMLDATA = _descriptor.Descriptor(
  name='DMLData',
  full_name='slave.binlog.DMLData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tables', full_name='slave.binlog.DMLData.tables', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=660,
)


_DDLDATA = _descriptor.Descriptor(
  name='DDLData',
  full_name='slave.binlog.DDLData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema_name', full_name='slave.binlog.DDLData.schema_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table_name', full_name='slave.binlog.DDLData.table_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ddl_query', full_name='slave.binlog.DDLData.ddl_query', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=662,
  serialized_end=731,
)


_BINLOG = _descriptor.Descriptor(
  name='Binlog',
  full_name='slave.binlog.Binlog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='slave.binlog.Binlog.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commit_ts', full_name='slave.binlog.Binlog.commit_ts', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dml_data', full_name='slave.binlog.Binlog.dml_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ddl_data', full_name='slave.binlog.Binlog.ddl_data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=895,
)

_ROW.fields_by_name['columns'].message_type = _COLUMN
_TABLE.fields_by_name['column_info'].message_type = _COLUMNINFO
_TABLE.fields_by_name['mutations'].message_type = _TABLEMUTATION
_TABLEMUTATION.fields_by_name['type'].enum_type = _MUTATIONTYPE
_TABLEMUTATION.fields_by_name['row'].message_type = _ROW
_TABLEMUTATION.fields_by_name['change_row'].message_type = _ROW
_DMLDATA.fields_by_name['tables'].message_type = _TABLE
_BINLOG.fields_by_name['type'].enum_type = _BINLOGTYPE
_BINLOG.fields_by_name['dml_data'].message_type = _DMLDATA
_BINLOG.fields_by_name['ddl_data'].message_type = _DDLDATA
DESCRIPTOR.message_types_by_name['Column'] = _COLUMN
DESCRIPTOR.message_types_by_name['ColumnInfo'] = _COLUMNINFO
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
DESCRIPTOR.message_types_by_name['TableMutation'] = _TABLEMUTATION
DESCRIPTOR.message_types_by_name['DMLData'] = _DMLDATA
DESCRIPTOR.message_types_by_name['DDLData'] = _DDLDATA
DESCRIPTOR.message_types_by_name['Binlog'] = _BINLOG
DESCRIPTOR.enum_types_by_name['MutationType'] = _MUTATIONTYPE
DESCRIPTOR.enum_types_by_name['BinlogType'] = _BINLOGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), dict(
  DESCRIPTOR = _COLUMN,
  __module__ = 'proto.binlog_pb2'
  # @@protoc_insertion_point(class_scope:slave.binlog.Column)
  ))
_sym_db.RegisterMessage(Column)

ColumnInfo = _reflection.GeneratedProtocolMessageType('ColumnInfo', (_message.Message,), dict(
  DESCRIPTOR = _COLUMNINFO,
  __module__ = 'proto.binlog_pb2'
  # @@protoc_insertion_point(class_scope:slave.binlog.ColumnInfo)
  ))
_sym_db.RegisterMessage(ColumnInfo)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
  DESCRIPTOR = _ROW,
  __module__ = 'proto.binlog_pb2'
  # @@protoc_insertion_point(class_scope:slave.binlog.Row)
  ))
_sym_db.RegisterMessage(Row)

Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), dict(
  DESCRIPTOR = _TABLE,
  __module__ = 'proto.binlog_pb2'
  # @@protoc_insertion_point(class_scope:slave.binlog.Table)
  ))
_sym_db.RegisterMessage(Table)

TableMutation = _reflection.GeneratedProtocolMessageType('TableMutation', (_message.Message,), dict(
  DESCRIPTOR = _TABLEMUTATION,
  __module__ = 'proto.binlog_pb2'
  # @@protoc_insertion_point(class_scope:slave.binlog.TableMutation)
  ))
_sym_db.RegisterMessage(TableMutation)

DMLData = _reflection.GeneratedProtocolMessageType('DMLData', (_message.Message,), dict(
  DESCRIPTOR = _DMLDATA,
  __module__ = 'proto.binlog_pb2'
  # @@protoc_insertion_point(class_scope:slave.binlog.DMLData)
  ))
_sym_db.RegisterMessage(DMLData)

DDLData = _reflection.GeneratedProtocolMessageType('DDLData', (_message.Message,), dict(
  DESCRIPTOR = _DDLDATA,
  __module__ = 'proto.binlog_pb2'
  # @@protoc_insertion_point(class_scope:slave.binlog.DDLData)
  ))
_sym_db.RegisterMessage(DDLData)

Binlog = _reflection.GeneratedProtocolMessageType('Binlog', (_message.Message,), dict(
  DESCRIPTOR = _BINLOG,
  __module__ = 'proto.binlog_pb2'
  # @@protoc_insertion_point(class_scope:slave.binlog.Binlog)
  ))
_sym_db.RegisterMessage(Binlog)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\310\342\036\001\340\342\036\001\320\342\036\001'))
_COLUMNINFO.fields_by_name['name'].has_options = True
_COLUMNINFO.fields_by_name['name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_COLUMNINFO.fields_by_name['mysql_type'].has_options = True
_COLUMNINFO.fields_by_name['mysql_type']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_COLUMNINFO.fields_by_name['is_primary_key'].has_options = True
_COLUMNINFO.fields_by_name['is_primary_key']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_BINLOG.fields_by_name['type'].has_options = True
_BINLOG.fields_by_name['type']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_BINLOG.fields_by_name['commit_ts'].has_options = True
_BINLOG.fields_by_name['commit_ts']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
# @@protoc_insertion_point(module_scope)
