# Importer Configuration.

log-level = "info"

worker-count = 10
job-count = 1000000
batch = 100

table-sql-dir = "/Users/xiang/newWorld/gopath/src/github.com/pingcap/tidb-tools/sqls"
ratio-file = "/Users/xiang/newWorld/gopath/src/github.com/pingcap/tidb-tools/atlas_wms.csv"
qps = 5000

[source-db]
host = "127.0.0.1"
user = "root"
password = "123456"
port = 3306
